-- MySQL Script generated by MySQL Workbench
-- Fri Jan  5 12:44:17 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `hw_zarizeni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hw_zarizeni` ;

CREATE TABLE IF NOT EXISTS `hw_zarizeni` (
  `unique_code` VARCHAR(20) NOT NULL,
  `nazev` VARCHAR(45) NOT NULL,
  `token` VARCHAR(45) NULL,
  PRIMARY KEY (`unique_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zaznam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zaznam` ;

CREATE TABLE IF NOT EXISTS `zaznam` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `uc_hw_zarizeni` VARCHAR(20) NULL,
  `nazev` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NOT NULL,
  `poloha` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NULL DEFAULT NULL,
  `mnozstvi` INT(11) NOT NULL DEFAULT 0,
  `datum_upravy` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `je_smazany` INT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_zaznam_hw_zarizeni1_idx` (`uc_hw_zarizeni` ASC),
  CONSTRAINT `fk_zaznam_hw_zarizeni`
    FOREIGN KEY (`uc_hw_zarizeni`)
    REFERENCES `hw_zarizeni` (`unique_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;


-- -----------------------------------------------------
-- Table `role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role` ;

CREATE TABLE IF NOT EXISTS `role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uzivatel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uzivatel` ;

CREATE TABLE IF NOT EXISTS `uzivatel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_role` INT NOT NULL,
  `login` VARCHAR(50) NOT NULL,
  `heslo` VARCHAR(60) NOT NULL,
  `jmeno` VARCHAR(50) NULL,
  `prijmeni` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  INDEX `fk_uzivatel_role_idx` (`id_role` ASC),
  CONSTRAINT `fk_uzivatel_role`
    FOREIGN KEY (`id_role`)
    REFERENCES `role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `udalost`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `udalost` ;

CREATE TABLE IF NOT EXISTS `udalost` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT NOT NULL,
  `barva` VARCHAR(20) NOT NULL DEFAULT '#0000FF',
  `datum` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `hw_zarizeni`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `hw_zarizeni` (`unique_code`, `nazev`, `token`) VALUES ('hw_a', 'Zařízení A', 'aaaa-aaaa');
INSERT INTO `hw_zarizeni` (`unique_code`, `nazev`, `token`) VALUES ('hw_b', 'Zařízení B', 'bbbb-bbbb');

COMMIT;


-- -----------------------------------------------------
-- Data for table `zaznam`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `zaznam` (`id`, `uc_hw_zarizeni`, `nazev`, `poloha`, `mnozstvi`, `datum_upravy`, `je_smazany`) VALUES (1, 'hw_a', 'Test zaznam A', 'regal_R', 30, DEFAULT, DEFAULT);
INSERT INTO `zaznam` (`id`, `uc_hw_zarizeni`, `nazev`, `poloha`, `mnozstvi`, `datum_upravy`, `je_smazany`) VALUES (2, 'hw_b', 'Test zaznam B', NULL, 0, DEFAULT, DEFAULT);
INSERT INTO `zaznam` (`id`, `uc_hw_zarizeni`, `nazev`, `poloha`, `mnozstvi`, `datum_upravy`, `je_smazany`) VALUES (3, NULL, 'Test zaznam C', 'skrin_S', 200, DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `role`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `role` (`id`, `nazev`) VALUES (1, 'SuperAdmin');
INSERT INTO `role` (`id`, `nazev`) VALUES (2, 'Admin');
INSERT INTO `role` (`id`, `nazev`) VALUES (3, 'Uzivatel');

COMMIT;


-- -----------------------------------------------------
-- Data for table `uzivatel`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `uzivatel` (`id`, `id_role`, `login`, `heslo`, `jmeno`, `prijmeni`) VALUES (1, 1, 'superadmin', 'superadmin', 'Super', 'Admin');
INSERT INTO `uzivatel` (`id`, `id_role`, `login`, `heslo`, `jmeno`, `prijmeni`) VALUES (2, 2, 'admin', 'admin', 'Normal', 'Admin');
INSERT INTO `uzivatel` (`id`, `id_role`, `login`, `heslo`, `jmeno`, `prijmeni`) VALUES (3, 3, 'uzivatel', 'uzivatel', 'Normální', 'Uživatel');

COMMIT;


-- -----------------------------------------------------
-- Data for table `udalost`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `udalost` (`id`, `text`, `barva`, `datum`) VALUES (DEFAULT, 'Sluníčko, 37°C', 'gold', DEFAULT);

COMMIT;

