-- MySQL Script generated by MySQL Workbench
-- Thu Oct 31 12:29:26 2019
-- Model: Základní databáze pro 6 cvičení.    Version: 1.0

-- Slouží pro cvičení z předmětu KIV/WEB na Západočeské univerzitě v Plzni.

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `orionlogin_pravo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orionlogin_pravo` ;

CREATE TABLE IF NOT EXISTS `orionlogin_pravo` (
  `id_pravo` INT NOT NULL,
  `nazev` VARCHAR(20) NOT NULL,
  `vaha` INT(2) NOT NULL,
  PRIMARY KEY (`id_pravo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;


-- -----------------------------------------------------
-- Table `orionlogin_uzivatel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orionlogin_uzivatel` ;

CREATE TABLE IF NOT EXISTS `orionlogin_uzivatel` (
  `id_uzivatel` INT NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(60) NOT NULL,
  `login` VARCHAR(30) NOT NULL,
  `heslo` VARCHAR(40) NOT NULL,
  `email` VARCHAR(35) NOT NULL,
  `id_pravo` INT NOT NULL DEFAULT 3,
  PRIMARY KEY (`id_uzivatel`),
  INDEX `fk_uzivatele_prava_orionlogin_idx` (`id_pravo` ASC),
  CONSTRAINT `fk_uzivatele_prava_orionlogin`
    FOREIGN KEY (`id_pravo`)
    REFERENCES `orionlogin_pravo` (`id_pravo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;


-- -----------------------------------------------------
-- Data for table `orionlogin_pravo`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `orionlogin_pravo` (`id_pravo`, `nazev`, `vaha`) VALUES (1, 'SuperAdmin', 20);
INSERT INTO `orionlogin_pravo` (`id_pravo`, `nazev`, `vaha`) VALUES (2, 'Admin', 10);
INSERT INTO `orionlogin_pravo` (`id_pravo`, `nazev`, `vaha`) VALUES (3, 'Recenzent', 5);
INSERT INTO `orionlogin_pravo` (`id_pravo`, `nazev`, `vaha`) VALUES (4, 'Autor', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `orionlogin_uzivatel`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `orionlogin_uzivatel` (`id_uzivatel`, `jmeno`, `login`, `heslo`, `email`, `id_pravo`) VALUES (1, 'Hlavní správce', 'admin', 'admin', 'pokus1@kiv.zcu.cz', 1);
INSERT INTO `orionlogin_uzivatel` (`id_uzivatel`, `jmeno`, `login`, `heslo`, `email`, `id_pravo`) VALUES (2, 'Pokusný recenzent', 'recenzent', 'recenzent', 'pokus2@kiv.zcu.cz', 3);
INSERT INTO `orionlogin_uzivatel` (`id_uzivatel`, `jmeno`, `login`, `heslo`, `email`, `id_pravo`) VALUES (3, 'Pokusný autor', 'autor', 'autor', 'pokus3@kiv.zcu.cz', 4);

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
