-- MySQL Script generated by MySQL Workbench
-- Wed Nov  6 11:56:13 2019
-- Model: Základní databáze pro 7. cvičení    Version: 1.0

-- Slouží pro cvičení z předmětu KIV/WEB na Západočeské univerzitě v Plzni.

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `orionlogin_mvc_introduction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orionlogin_mvc_introduction` ;

CREATE TABLE IF NOT EXISTS `orionlogin_mvc_introduction` (
  `id_introduction` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `author` VARCHAR(100) NOT NULL,
  `title` VARCHAR(150) NOT NULL,
  `text` TEXT NOT NULL,
  PRIMARY KEY (`id_introduction`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orionlogin_mvc_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orionlogin_mvc_user` ;

CREATE TABLE IF NOT EXISTS `orionlogin_mvc_user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  `web` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Data for table `orionlogin_mvc_introduction`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `orionlogin_mvc_introduction` (`id_introduction`, `date`, `author`, `title`, `text`) VALUES (DEFAULT, '2016-10-28 15:02:00', 'Bratři Grimmové', 'Divous a princátko', 'Byl jednou jeden divous, který byl zakletý, a ten chodil sedlákům do polí a zahrad, kde dupal a ničil úrodu, a tak jim dělal převelikou škodu. Ubozí sedláci si stěžovali vrchnosti, že dál nemohou platit pachtovné, a tak nechal pán sezvat všechny lovce ze široka daleka; kdo divouse chytí, ten dostane obrovskou odměnu. Tu tam přišel jeden starý lovec, který tvrdil, že ho chytí, ale musejí mu dát sud pálenky, sud vína a sud piva; a pak s tím odešel k prameni, kde se divous každý den myl. On sám se postavil za strom a čekal, tu přišlo to divé chlapisko, všechno to vypilo, pak ještě sudy vylízalo a vrávoralo dokola, zda ještě někde něco nenajde. Ale bylo pěkně opilé, a tak se svalilo a usnulo. Tu k němu přišel lovec, svázal ho na rukou i nohou, probudil ho a řekl: „Divousi, teď pojď se mnou, dostaneš napít každý den.“ A odvedl ho na šlechtický zámek, kde ho posadili do klece, zatímco pán jel pro sousedy, aby se podívali, co to chytili za tvora. Jedno z princátek si ale hrálo na dvoře s míčem a ten mu spadl do klece, a tak řeklo: „Divousi, hoď mi ten míč zpět.“ Ale ten řekl: „Jen si ho vezmi sám.“ „Rád,“ řeklo: „ale nemám klíč.“ „Tak se snaž, ať se dostaneš matce do kapsy a ten klíč jí ukradneš.“ To se princátku podařilo, klec otevřelo, ale v tom vylezl divous ven, a tak se jalo křičet: „Divousi, divousi, zůstaň tady nebo dostanu výprask!“ Tak si ho divous hodil na záda a utíkal s ním cestou, necestou, stále hloub a hloub do lesa. A bylo to! Když se hradní pán vrátil, byl divous pryč a princátko ztracené!');
INSERT INTO `orionlogin_mvc_introduction` (`id_introduction`, `date`, `author`, `title`, `text`) VALUES (DEFAULT, '2016-11-01 10:53:00', 'Johann Wilhelm Wolf', 'Houslista a tancující prasátka', 'Byl jednou jeden hrabě a ten si držel na svém zámku houslistu, který mu velmi krásně hrával a zaháněl mu tím špatnou náladu. Jednoho dne ale hrabě umřel a chudý houslista přišel o svoji obživu, neboť dědicové ho ze zámku vykázali a nechali jít žebrotou. Tak hrál na svoje housle před dveřmi chudých i bohatých, tu dostal peníz, tu chleba, ale bylo to pro něj dost tvrdé živobytí, protože předtím si žil lépe, a tak byl často opravdu zachmuřený, často blíž pláči než ke smíchu');
INSERT INTO `orionlogin_mvc_introduction` (`id_introduction`, `date`, `author`, `title`, `text`) VALUES (DEFAULT, '2016-11-01 12:36:10', 'Joseph Haltrich', 'Jak Rozum se Štěstím vandrovali', 'Kdysi dávno se vydali Rozum a Štěstí do světa, aby si ho prohlédli a lidi potěšili svými dary. Jak tak putovali, uviděli jednou, jak u cesty spí ovčák. „Víš ty co?“ řeklo Štěstí Rozumu: „Vyzkoušíme si ty naše dary. Vlez si do něj!“ Rozumu to bylo po té dlouhé štrapáci právě vhod, a tak se usadil v hochově hlavě a pěkně si tam hověl. Když se ovčák probudil, promnul si oči a ejhle! Hned tu byla myšlenka: „Ej, k čemu tu pást ovce, pro jednou vyzkouším svoje štěstí i ve městě!“');
INSERT INTO `orionlogin_mvc_introduction` (`id_introduction`, `date`, `author`, `title`, `text`) VALUES (DEFAULT, '2016-11-03 08:16:36', 'Ulrich Jahn', 'Jak Rozum pokoušel Štěstí', 'Jednou se rozum vydal na cestu se štěstím a takto si rozumoval: „Komu pomáhám, tomu se dobře daří.“ „To by se muselo vyzkoušet.“ opáčilo štěstí, což vedlo k vádě a hašteření, když tu se jim nachomýtl do rány selský synek, který tam se dvěma kravami oral pole. „Ten hoch se mi líbí!“ zvolal rozum: „Co myslíš, štěstí, kdybychom si ho vyzkoušeli?“ Štěstí spokojeně mlasklo, a tak rozum, který má vždy navrch a ustavičně chce být ten první, vpadl hochovi do zad tak prudce, že písnička, kterou si do té chvíle jen tak pro sebe pískal, jak už si tak rolníci při práci pískají, vzala za konec, hoch se zarazil a zamyšleně pozoroval brázdy. Tu viděl, že jedna je rovná a přímá jako druhá, a kdo umí orat, dobře ví, co to znamená, aby jeden uměl brázdy jako střižené. „Hochu, hochu“ pomyslel si: „jsi ještě tak mladý a už umíš tak výtečně orat? Na sedláka je tě škoda!“ A čile vypřáhl krávy a obrátil zpět k domovu na dvůr. „Matko,“ řekl: „být sedlákem to není nic pro mne, chci do města a vyučit se řemeslu.“ Jeho matka ale byla vdova a hoch její jediný syn a opora a dědic statku, a tak řekla na ta slova rozzlobeně: „Kdo ti nasadil takového pavouka do hlavy? Ihned se vrátíš na pole a nepřijdeš mi na oči před večerem!“ Hoch nakonec poslechl a svoji práci vykonal.');

COMMIT;


-- -----------------------------------------------------
-- Data for table `orionlogin_mvc_user`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `orionlogin_mvc_user` (`id_user`, `first_name`, `last_name`, `login`, `password`, `email`, `web`) VALUES (DEFAULT, 'František', 'Novák', 'nofr', 'abcdefgh', 'fra.novak@gmail.com', 'www.google.com');
INSERT INTO `orionlogin_mvc_user` (`id_user`, `first_name`, `last_name`, `login`, `password`, `email`, `web`) VALUES (DEFAULT, 'Eduard', 'Hlávka', 'hlavka', '1234', 'hlavka.eduard@seznam.cz', 'www.seznam.cz');
INSERT INTO `orionlogin_mvc_user` (`id_user`, `first_name`, `last_name`, `login`, `password`, `email`, `web`) VALUES (DEFAULT, 'Kamila', 'Urbanová', 'kamila', 'kamil', 'urbanova@centrum.cz', 'www.centrum.cz');
INSERT INTO `orionlogin_mvc_user` (`id_user`, `first_name`, `last_name`, `login`, `password`, `email`, `web`) VALUES (DEFAULT, 'Jana', 'Molová', 'jamol', '101112', 'jamol@yahoo.com', 'www.yahoo.com');

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
